#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# 添加python库的include路径
python_dir = "C:/Users/yanyan/AppData/Local/Programs/Python/Python312"
env.Append(CPPPATH=[os.path.join(python_dir, "include")])
env.Append(CPPPATH=[os.path.join(python_dir, "Lib/site-packages/pybind11/include")])
env.Append(LIBPATH=[os.path.join(python_dir, "libs")])
env.Append(LINKFLAGS=["python3.lib","python312.lib"])



# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "demo/bin/libgdexample.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "bin/libgdexample{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
